name: PtProBuild
'on':
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: adopt
      - name: Build With Gradle
        run: ./gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: PtProReleased.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build app bundle
        run: ./gradlew bundleRelease

      - name: Sign app bundle
        run: 
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 
          -keystore SignApk/PtProKeyStore.jks 
          -storepass "ptbeta@2410" 
          -keypass "ptbeta@2410" 
          SignApk/app.aab 
          key0